name: generate-pages-tag
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
      - run: ls
      - run: python make-tag.py
      
